---
- name: Migrate to Rocky Linux
  hosts: all
  tasks:
    - name: Download migrate2rocky.sh script
      get_url:
        url: "https://raw.githubusercontent.com/rocky-linux/rocky-tools/main/migrate2rocky/migrate2rocky.sh"
        dest: "/tmp/migrate2rocky.sh"
        mode: '0755'

    - name: Execute migrate2rocky.sh script
      command: "/tmp/migrate2rocky.sh -r"
      become: yes  # This ensures the task runs with sudo privileges
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines
